### ISSUE TITLE
Errors in schemas

### ISSUE THREAD

**Issue by jirutka** [dahag-ag/keycloak-openapi#7]
I’ve added `additionalProperties: false' to all of the objects and validated realm export to check that all of the properties are actually defined in the schemas (for 21.0.0). There are my findings.

```diff
  RealmRepresentation:
    properties:
-     oAuth2DeviceCodeLifespan:
+     oauth2DeviceCodeLifespan:
-     oAuth2DevicePollingInterval
+     oauth2DevicePollingInterval
+     clientPolicies:
+       $ref: "#/components/schemas/ClientPoliciesRepresentation"
+     clientProfiles:
+       $ref: "#/components/schemas/ClientProfilesRepresentation"
    components:
       additionalProperties:
-        $ref: "#/components/schemas/ComponentExportRepresentation"
+        type: array
+        items:
+          $ref: "#/components/schemas/ComponentExportRepresentation"

  ClientPoliciesRepresentation:
    properties:
      policies:
        type: array
        items:
-         type: object
-         description: ClientPolicyRepresentation
+         $ref: "#/components/schemas/ClientPolicyRepresentation"

+ ClientPolicyRepresentation:

  ComponentExportRepresentation:
    properties:
      config:
        additionalProperties:
-         type: string
+         type: array
+         items:
+           type: string
      subComponents:
        additionalProperties:
-         $ref: "#/components/schemas/ComponentExportRepresentation"
+         type: array
+         items:
+           $ref: "#/components/schemas/ComponentExportRepresentation"

  PolicyRepresentation:
    properties:
+     // + all properties from AbstractPolicyRepresentation

  AuthenticationExecutionExportRepresentation:
    properties:
+     // + all properties from AbstractAuthenticationExecutionRepresentation
```

* [ClientPolicyRepresentation](https://github.com/keycloak/keycloak/blob/main/core/src/main/java/org/keycloak/representations/idm/ClientPolicyRepresentation.java) is missing in the scheme.
* [PolicyRepresentation](https://github.com/keycloak/keycloak/blob/main/core/src/main/java/org/keycloak/representations/idm/authorization/PolicyRepresentation.java) extends [AbstractPolicyRepresentation](https://github.com/keycloak/keycloak/blob/main/core/src/main/java/org/keycloak/representations/idm/authorization/AbstractPolicyRepresentation.java) – both are in the scheme, but it doesn’t reflect that the former extends the latter.
* [AuthenticationExecutionExportRepresentation](https://github.com/keycloak/keycloak/blob/main/core/src/main/java/org/keycloak/representations/idm/AuthenticationExecutionExportRepresentation.java) extends [AbstractAuthenticationExecutionRepresentation](https://github.com/keycloak/keycloak/blob/main/core/src/main/java/org/keycloak/representations/idm/AbstractAuthenticationExecutionRepresentation.java) – both are in the scheme, but it doesn’t reflect that the former extends the latter.

**Comment by DAHAG-ArisNourbakhsh** [comment]
About `ClientPoliciesRepresentation`: I hardcoded that to be ignored due to an ambiguation issue. There are two in different namespaces, one in `org.keycloak.representations.idm` and another in `org.keycloak.representations.idm.authorization`. The issue with that is I do very simple string name matching on any property that references a type. So if I wanted to properly figure out which of them it is I'd have to track the namespace of each class and also analyse which namespace the usage is referring to.

I felt and still feel hesitant to properly add logic for that because it's only this one file that has an ambiguation issue and I fear this might add a lot of complexity.

The lack of handling polymorphism is due to the same reason: too much work for too little gain

**Comment by jirutka** [comment]
> The lack of handling polymorphism is due to the same reason: too much work for too little gain

I wouldn’t consider having a schema that can really validate a valid realm export is a little gain…
However, I understand that properly handling this in the generator would add a lot to its complexity. It might be much easier to solve this in post-processing – not universally, but on a case-by-case basis. Most of the schema seems correct, just some special cases need special handling.
